# Generated by Django 4.2.1 on 2024-05-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_ingresosmensuales'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
