# Generated by Django 4.2.1 on 2024-05-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_socio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
