# Generated by Django 4.2.1 on 2024-05-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_socio_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
