# Generated by Django 5.0 on 2024-05-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_pago_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='entrada_permitida',
            field=models.BooleanField(default=True),
        ),
    ]
